export const SET_TITLES = 'SET_TITLES'
export const RESET_TITLES = 'RESET_TITLES'
export const ADD_GENRE_FILTER = 'ADD_GENRE_FILTER'
export const REMOVE_GENRE_FILTER = 'REMOVE_GENRE_FILTER'
export const SET_RATING_FILTER = 'SET_RATING_FILTER'
export const SORT_BY = 'SORT_BY'
export const CHANGE_DEFAULT_SORT = 'CHANGE_DEFAULT_SORT'


export const LOGIN_START = 'LOGIN_START'
export const LOGIN = 'LOGIN'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'


export const UPDATE_RATINGS = 'UPDATE_RATINGS'

export const SET_COMMENTS = 'SET_COMMENTS'
export const ADD_COMMENT = 'ADD_COMMENT'
export const REMOVE_COMMNET = 'REMOVE_COMMNENT'
export const ADD_RATING = 'ADD_RATING'
export const REMOVE_RATING = 'REMOVE_RATING'